### ISSUE TITLE
Env detection not working as expected

### ISSUE THREAD

**Issue by baztian** [ryanhiebert/tox-travis#62]
I'm trying to a travis matrix to tox.
`.travis.yml`

```yaml
python:
  - '2.6'
  - '2.7'
  - '3.4'

env:
  matrix:
    include:
      - python: 3.4
        env: JYTHON="org.python;jython-installer;2.7.0"
```

`tox.ini`

```ini
[tox]
envlist = py{26,27,3}-driver-{hsqldb,mock,sqliteXerial},py27-driver-sqlitePy,jython-driver-{hsqldb,mock}

[travis]
python =
  2.6: py26-driver-{hsqldb,mock,sqliteXerial}
  2.7: py27-driver-{hsqldb,mock,sqliteXerial,sqlitePy}
  3.4: py34-driver-{hsqldb,mock,sqliteXerial}

[travis:env]
JYTHON =
  org.python;jython-installer;2.7.0: jython-driver-{hsqldb,mock}
```

(You can find the real code in [my feature branch](/baztian/jaydebeapi/tree/travis-tox))

[The build](https://travis-ci.org/baztian/jaydebeapi/builds/209340861) runs fine (the error is not related to tox mapping problems). But the Python 3.4 + Jython-Env entry doesn't get mapped as desired. It maps to all tox environments whereas I was expecting it to match to just the Jython environments (`jython-driver-{hsqldb,mock}`).

Am I doing something wrong or is this a bug?
