### ISSUE TITLE
Using with PyPy 3 5.5?

### ISSUE THREAD

**Issue by kirbyfan64** [ryanhiebert/tox-travis#65]
[I'm stuck...](https://github.com/berkerpeksag/astor/pull/56)

Right now, I have:

## travis.yml

```yaml
sudo: false  # run travis jobs in containers
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - pypy
  - "pypy3.3-5.5-alpha"
cache:
  directories:
    - $PWD/wheelhouse  # cache wheels so that we don't hit network everytime
env:
  global:
    - PIP_FIND_LINKS=$PWD/wheelhouse
install:
  - pip install tox-travis
script: tox
```

## tox.ini

```ini
[tox]
envlist = py26, py27, py33, py34, pypy, pypy3.3-5.5-alpha
skipsdist = True

[testenv]
usedevelop = True
commands = nosetests
deps =
 -rrequirements-tox.txt
 py26: unittest2
```

Travis reports that the PyPy3 version is 5.5, which is compatible with Python 3.3.5. BUT, when *pip* is run, it ends up (somehow?) using an old PyPy3 version and fails.

As a random guess, maybe [this line](https://github.com/ryanhiebert/tox-travis/blob/master/src/tox_travis/toxenv.py#L49) should also check for PyPy 5.5?
