### ISSUE TITLE
Coverage % changed using tox-travis

### ISSUE THREAD

**Issue by fabiocaccamo** [ryanhiebert/tox-travis#67]
Hi @ryanhiebert , 
thanks for this great plugin.

I just tried it and everything works fine, except the fact that the coverage is decreased, before it was 100% and now it's 98% because some code is executed only on specific django versions.

When I run tox ( `coverage run --append ...` ) the coverage is 100%.
It seems that the --append option doesn't work properly.

This is the involved repo: https://github.com/fabiocaccamo/django-maintenance-mode

**Comment by rpkilby** [comment]
No idea if this is the case. Each tox run is uploading a separate report using the same environment variables and build id. It doesn't look like anything distinguishes the django version. Maybe codecov is considering the separate runs as duplicate? 

I would try running the codecov step out of the tox config and into the travis config. Maybe something like:

```yaml
after_success:
  - coverage combine --append
  - coverage report -m
  - pip install codecov
  - codecov
```

**Comment by ryanhiebert** [comment]
codecov/support#132 suggests that they may not be combining uploads appropriately when there are multiple uploads from the same travis job. I can't confirm that, but that would line up well with the symptoms.

One thing that I suspect you did accidentally, @fabiocaccamo, is that in your transition to using tox-travis you actually dropped the number of jobs you're running to just one per python version. I'd recommend adding the following to your configuration files, so that you're running one Travis job for each of your Tox envs:

### tox.ini

```ini
[travis:env]
DJANGO =
  1.7: 17
  1.8: 18
  1.9: 19
  1.10: 110
```

### .travis.yml

```yaml
# Merge this into your current file as appropriate
env:
  - DJANGO="1.7"
  - DJANGO="1.8"
  - DJANGO="1.9"
  - DJANGO="1.10"
matrix:
  exclude:
    - python: 3.5
      env: DJANGO="1.7"
    - python: 3.6
      env: DJANGO="1.7"
```

----

At that point, since each Travis job will only be running one Tox env, there won't be any reason to use the append flag for coverage. The file won't exist anyway.
